# Generated by Django 4.2.5 on 2023-09-22 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150, verbose_name='Category name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
        ),
        migrations.CreateModel(
            name='FoodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Title')),
                ('about', models.TextField(verbose_name='About')),
                ('exclusive', models.BooleanField(default=False, verbose_name='Exclusive')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.DecimalValidator(decimal_places=2, max_digits=5)], verbose_name='Price')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('category', models.ManyToManyField(to='dingoapp.category', verbose_name='Category')),
            ],
        ),
    ]
