# Generated by Django 4.2.5 on 2023-09-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dingoapp', '0002_foodmodel_picture_alter_foodmodel_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chef_name', models.TextField(max_length=150, verbose_name='Chef name')),
                ('chef_ct', models.TextField(max_length=150, verbose_name='Chef ct')),
            ],
        ),
        migrations.AlterField(
            model_name='foodmodel',
            name='picture',
            field=models.ImageField(default='/media/food/logo.png', upload_to='food/'),
        ),
    ]
