# Generated by Django 4.2.5 on 2023-10-03 12:34

import dingoapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dingoapp', '0004_bookingmodel_cheflevel_chefs_delete_chefmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='time',
            field=models.TimeField(validators=[dingoapp.models.past_time_validator], verbose_name='Time'),
        ),
    ]
